# Generated by Django 4.2.4 on 2023-09-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название коллекции')),
                ('photo1', models.ImageField(upload_to='collection_images/', verbose_name='фотография')),
                ('photo2', models.ImageField(upload_to='collection_images/', verbose_name='фотография')),
                ('photo3', models.ImageField(upload_to='collection_images/', verbose_name='фотография')),
                ('photo4', models.ImageField(upload_to='collection_images/', verbose_name='фотография')),
                ('photo5', models.ImageField(upload_to='collection_images/', verbose_name='фотография')),
                ('photo6', models.ImageField(upload_to='collection_images/', verbose_name='фотография')),
                ('photo7', models.ImageField(upload_to='collection_images/', verbose_name='фотография')),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название платья')),
                ('compound', models.CharField(max_length=255, verbose_name='состав')),
                ('color', models.CharField(max_length=255, verbose_name='цвет')),
                ('price', models.CharField(max_length=255, verbose_name='цена')),
                ('product_article', models.CharField(max_length=255, verbose_name='артикул')),
                ('image1', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image2', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image3', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image4', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
            ],
        ),
        migrations.CreateModel(
            name='Jackets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название пиджака')),
                ('compound', models.CharField(max_length=255, verbose_name='состав')),
                ('color', models.CharField(max_length=255, verbose_name='цвет')),
                ('price', models.CharField(max_length=255, verbose_name='цена')),
                ('product_article', models.CharField(max_length=255, verbose_name='артикул')),
                ('image1', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image2', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image3', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image4', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
            ],
        ),
        migrations.CreateModel(
            name='New_collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название коллекции')),
                ('compound', models.CharField(max_length=255, verbose_name='состав')),
                ('color', models.CharField(max_length=255, verbose_name='цвет')),
                ('price', models.CharField(max_length=255, verbose_name='цена')),
                ('product_article', models.CharField(max_length=255, verbose_name='артикул')),
                ('image1', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image2', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image3', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image4', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
            ],
        ),
        migrations.CreateModel(
            name='Shirts_and_blouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название рубашки или блузы')),
                ('compound', models.CharField(max_length=255, verbose_name='состав')),
                ('color', models.CharField(max_length=255, verbose_name='цвет')),
                ('price', models.CharField(max_length=255, verbose_name='цена')),
                ('product_article', models.CharField(max_length=255, verbose_name='артикул')),
                ('image1', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image2', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image3', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image4', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
            ],
        ),
        migrations.CreateModel(
            name='Trousers_and_skirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название брюк или юбки')),
                ('compound', models.CharField(max_length=255, verbose_name='состав')),
                ('color', models.CharField(max_length=255, verbose_name='цвет')),
                ('price', models.CharField(max_length=255, verbose_name='цена')),
                ('product_article', models.CharField(max_length=255, verbose_name='артикул')),
                ('image1', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image2', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image3', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image4', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
            ],
        ),
    ]
