# Generated by Django 4.2.4 on 2023-10-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название платья')),
                ('compound', models.CharField(max_length=255, verbose_name='состав')),
                ('color', models.CharField(max_length=255, verbose_name='цвет')),
                ('price', models.CharField(max_length=255, verbose_name='цена')),
                ('product_article', models.CharField(max_length=255, verbose_name='артикул')),
                ('image1', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image2', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image3', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image4', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
            ],
        ),
        migrations.CreateModel(
            name='Jackets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название пиджака')),
                ('compound', models.CharField(max_length=255, verbose_name='состав')),
                ('color', models.CharField(max_length=255, verbose_name='цвет')),
                ('price', models.CharField(max_length=255, verbose_name='цена')),
                ('product_article', models.CharField(max_length=255, verbose_name='артикул')),
                ('image1', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image2', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image3', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image4', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
            ],
        ),
        migrations.CreateModel(
            name='NewCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название коллекции')),
                ('compound', models.CharField(max_length=255, verbose_name='состав')),
                ('color', models.CharField(max_length=255, verbose_name='цвет')),
                ('price', models.CharField(max_length=255, verbose_name='цена')),
                ('product_article', models.CharField(max_length=255, verbose_name='артикул')),
                ('image1', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image2', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image3', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image4', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='ShirtsAndBlouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название рубашки или блузы')),
                ('compound', models.CharField(max_length=255, verbose_name='состав')),
                ('color', models.CharField(max_length=255, verbose_name='цвет')),
                ('price', models.CharField(max_length=255, verbose_name='цена')),
                ('product_article', models.CharField(max_length=255, verbose_name='артикул')),
                ('image1', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image2', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image3', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image4', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
            ],
        ),
        migrations.CreateModel(
            name='TrousersAndSkirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название брюк или юбки')),
                ('compound', models.CharField(max_length=255, verbose_name='состав')),
                ('color', models.CharField(max_length=255, verbose_name='цвет')),
                ('price', models.CharField(max_length=255, verbose_name='цена')),
                ('product_article', models.CharField(max_length=255, verbose_name='артикул')),
                ('image1', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image2', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image3', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
                ('image4', models.ImageField(upload_to='product_images/', verbose_name='фотография')),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название коллекции')),
                ('collection_photo', models.ImageField(upload_to='', verbose_name='фотография')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('photos', models.ManyToManyField(to='mikhalchuk.photo')),
            ],
        ),
    ]
