# Generated by Django 4.2.4 on 2023-10-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikhalchuk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ManyToManyField(to='mikhalchuk.photo')),
            ],
        ),
    ]
