# Generated by Django 4.2.4 on 2023-09-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikhalchuk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='photo6',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='photo7',
        ),
    ]
